CREATE TABLE "selected_periods" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "selected_periods_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"student_id" uuid NOT NULL,
	"period_id" integer NOT NULL,
	CONSTRAINT "selected_periods_student_id_unique" UNIQUE("student_id")
);
--> statement-breakpoint
ALTER TABLE "selected_periods" ADD CONSTRAINT "selected_periods_student_id_students_id_fk" FOREIGN KEY ("student_id") REFERENCES "public"."students"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "selected_periods" ADD CONSTRAINT "selected_periods_period_id_academic_periods_id_fk" FOREIGN KEY ("period_id") REFERENCES "public"."academic_periods"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "selected_periods_period_id_idx" ON "selected_periods" USING btree ("period_id");