/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedSubjectsRouteImport } from './routes/_authed/subjects'
import { Route as AuthedSchedulesRouteImport } from './routes/_authed/schedules'
import { Route as AuthedRegistrationFormRouteImport } from './routes/_authed/registration-form'
import { Route as AuthedGradesRouteImport } from './routes/_authed/grades'
import { Route as AuthedAccountRouteImport } from './routes/_authed/account'

const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedSubjectsRoute = AuthedSubjectsRouteImport.update({
  id: '/subjects',
  path: '/subjects',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSchedulesRoute = AuthedSchedulesRouteImport.update({
  id: '/schedules',
  path: '/schedules',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedRegistrationFormRoute = AuthedRegistrationFormRouteImport.update({
  id: '/registration-form',
  path: '/registration-form',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedGradesRoute = AuthedGradesRouteImport.update({
  id: '/grades',
  path: '/grades',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAccountRoute = AuthedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AuthedAccountRoute
  '/grades': typeof AuthedGradesRoute
  '/registration-form': typeof AuthedRegistrationFormRoute
  '/schedules': typeof AuthedSchedulesRoute
  '/subjects': typeof AuthedSubjectsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AuthedAccountRoute
  '/grades': typeof AuthedGradesRoute
  '/registration-form': typeof AuthedRegistrationFormRoute
  '/schedules': typeof AuthedSchedulesRoute
  '/subjects': typeof AuthedSubjectsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/_authed/account': typeof AuthedAccountRoute
  '/_authed/grades': typeof AuthedGradesRoute
  '/_authed/registration-form': typeof AuthedRegistrationFormRoute
  '/_authed/schedules': typeof AuthedSchedulesRoute
  '/_authed/subjects': typeof AuthedSubjectsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/grades'
    | '/registration-form'
    | '/schedules'
    | '/subjects'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/grades'
    | '/registration-form'
    | '/schedules'
    | '/subjects'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/_authed/account'
    | '/_authed/grades'
    | '/_authed/registration-form'
    | '/_authed/schedules'
    | '/_authed/subjects'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/subjects': {
      id: '/_authed/subjects'
      path: '/subjects'
      fullPath: '/subjects'
      preLoaderRoute: typeof AuthedSubjectsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/schedules': {
      id: '/_authed/schedules'
      path: '/schedules'
      fullPath: '/schedules'
      preLoaderRoute: typeof AuthedSchedulesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/registration-form': {
      id: '/_authed/registration-form'
      path: '/registration-form'
      fullPath: '/registration-form'
      preLoaderRoute: typeof AuthedRegistrationFormRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/grades': {
      id: '/_authed/grades'
      path: '/grades'
      fullPath: '/grades'
      preLoaderRoute: typeof AuthedGradesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/account': {
      id: '/_authed/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthedAccountRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedAccountRoute: typeof AuthedAccountRoute
  AuthedGradesRoute: typeof AuthedGradesRoute
  AuthedRegistrationFormRoute: typeof AuthedRegistrationFormRoute
  AuthedSchedulesRoute: typeof AuthedSchedulesRoute
  AuthedSubjectsRoute: typeof AuthedSubjectsRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedAccountRoute: AuthedAccountRoute,
  AuthedGradesRoute: AuthedGradesRoute,
  AuthedRegistrationFormRoute: AuthedRegistrationFormRoute,
  AuthedSchedulesRoute: AuthedSchedulesRoute,
  AuthedSubjectsRoute: AuthedSubjectsRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
