/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedSubjectsRouteImport } from './routes/_authed/subjects'
import { Route as AuthedSchedulesRouteImport } from './routes/_authed/schedules'
import { Route as AuthedRegistrationFormRouteImport } from './routes/_authed/registration-form'
import { Route as AuthedGradesRouteImport } from './routes/_authed/grades'
import { Route as AuthedAccountRouteImport } from './routes/_authed/account'
import { Route as AuthedSettingsRouteRouteImport } from './routes/_authed/settings/route'
import { Route as AuthedEnrollRouteRouteImport } from './routes/_authed/enroll/route'
import { Route as AuthedSettingsIndexRouteImport } from './routes/_authed/settings/index'
import { Route as AuthedEnrollIndexRouteImport } from './routes/_authed/enroll/index'
import { Route as AuthedSettingsDeleteRouteImport } from './routes/_authed/settings/delete'
import { Route as AuthedSettingsAuthRouteImport } from './routes/_authed/settings/auth'
import { Route as AuthedEnrollEncodeRouteImport } from './routes/_authed/enroll/encode'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedSubjectsRoute = AuthedSubjectsRouteImport.update({
  id: '/subjects',
  path: '/subjects',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSchedulesRoute = AuthedSchedulesRouteImport.update({
  id: '/schedules',
  path: '/schedules',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedRegistrationFormRoute = AuthedRegistrationFormRouteImport.update({
  id: '/registration-form',
  path: '/registration-form',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedGradesRoute = AuthedGradesRouteImport.update({
  id: '/grades',
  path: '/grades',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAccountRoute = AuthedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsRouteRoute = AuthedSettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedEnrollRouteRoute = AuthedEnrollRouteRouteImport.update({
  id: '/enroll',
  path: '/enroll',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsIndexRoute = AuthedSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedSettingsRouteRoute,
} as any)
const AuthedEnrollIndexRoute = AuthedEnrollIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedEnrollRouteRoute,
} as any)
const AuthedSettingsDeleteRoute = AuthedSettingsDeleteRouteImport.update({
  id: '/delete',
  path: '/delete',
  getParentRoute: () => AuthedSettingsRouteRoute,
} as any)
const AuthedSettingsAuthRoute = AuthedSettingsAuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => AuthedSettingsRouteRoute,
} as any)
const AuthedEnrollEncodeRoute = AuthedEnrollEncodeRouteImport.update({
  id: '/encode',
  path: '/encode',
  getParentRoute: () => AuthedEnrollRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/register': typeof RegisterRoute
  '/enroll': typeof AuthedEnrollRouteRouteWithChildren
  '/settings': typeof AuthedSettingsRouteRouteWithChildren
  '/account': typeof AuthedAccountRoute
  '/grades': typeof AuthedGradesRoute
  '/registration-form': typeof AuthedRegistrationFormRoute
  '/schedules': typeof AuthedSchedulesRoute
  '/subjects': typeof AuthedSubjectsRoute
  '/enroll/encode': typeof AuthedEnrollEncodeRoute
  '/settings/auth': typeof AuthedSettingsAuthRoute
  '/settings/delete': typeof AuthedSettingsDeleteRoute
  '/enroll/': typeof AuthedEnrollIndexRoute
  '/settings/': typeof AuthedSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/register': typeof RegisterRoute
  '/account': typeof AuthedAccountRoute
  '/grades': typeof AuthedGradesRoute
  '/registration-form': typeof AuthedRegistrationFormRoute
  '/schedules': typeof AuthedSchedulesRoute
  '/subjects': typeof AuthedSubjectsRoute
  '/enroll/encode': typeof AuthedEnrollEncodeRoute
  '/settings/auth': typeof AuthedSettingsAuthRoute
  '/settings/delete': typeof AuthedSettingsDeleteRoute
  '/enroll': typeof AuthedEnrollIndexRoute
  '/settings': typeof AuthedSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/register': typeof RegisterRoute
  '/_authed/enroll': typeof AuthedEnrollRouteRouteWithChildren
  '/_authed/settings': typeof AuthedSettingsRouteRouteWithChildren
  '/_authed/account': typeof AuthedAccountRoute
  '/_authed/grades': typeof AuthedGradesRoute
  '/_authed/registration-form': typeof AuthedRegistrationFormRoute
  '/_authed/schedules': typeof AuthedSchedulesRoute
  '/_authed/subjects': typeof AuthedSubjectsRoute
  '/_authed/enroll/encode': typeof AuthedEnrollEncodeRoute
  '/_authed/settings/auth': typeof AuthedSettingsAuthRoute
  '/_authed/settings/delete': typeof AuthedSettingsDeleteRoute
  '/_authed/enroll/': typeof AuthedEnrollIndexRoute
  '/_authed/settings/': typeof AuthedSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/register'
    | '/enroll'
    | '/settings'
    | '/account'
    | '/grades'
    | '/registration-form'
    | '/schedules'
    | '/subjects'
    | '/enroll/encode'
    | '/settings/auth'
    | '/settings/delete'
    | '/enroll/'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/register'
    | '/account'
    | '/grades'
    | '/registration-form'
    | '/schedules'
    | '/subjects'
    | '/enroll/encode'
    | '/settings/auth'
    | '/settings/delete'
    | '/enroll'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/register'
    | '/_authed/enroll'
    | '/_authed/settings'
    | '/_authed/account'
    | '/_authed/grades'
    | '/_authed/registration-form'
    | '/_authed/schedules'
    | '/_authed/subjects'
    | '/_authed/enroll/encode'
    | '/_authed/settings/auth'
    | '/_authed/settings/delete'
    | '/_authed/enroll/'
    | '/_authed/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/subjects': {
      id: '/_authed/subjects'
      path: '/subjects'
      fullPath: '/subjects'
      preLoaderRoute: typeof AuthedSubjectsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/schedules': {
      id: '/_authed/schedules'
      path: '/schedules'
      fullPath: '/schedules'
      preLoaderRoute: typeof AuthedSchedulesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/registration-form': {
      id: '/_authed/registration-form'
      path: '/registration-form'
      fullPath: '/registration-form'
      preLoaderRoute: typeof AuthedRegistrationFormRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/grades': {
      id: '/_authed/grades'
      path: '/grades'
      fullPath: '/grades'
      preLoaderRoute: typeof AuthedGradesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/account': {
      id: '/_authed/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthedAccountRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings': {
      id: '/_authed/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthedSettingsRouteRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/enroll': {
      id: '/_authed/enroll'
      path: '/enroll'
      fullPath: '/enroll'
      preLoaderRoute: typeof AuthedEnrollRouteRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings/': {
      id: '/_authed/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthedSettingsIndexRouteImport
      parentRoute: typeof AuthedSettingsRouteRoute
    }
    '/_authed/enroll/': {
      id: '/_authed/enroll/'
      path: '/'
      fullPath: '/enroll/'
      preLoaderRoute: typeof AuthedEnrollIndexRouteImport
      parentRoute: typeof AuthedEnrollRouteRoute
    }
    '/_authed/settings/delete': {
      id: '/_authed/settings/delete'
      path: '/delete'
      fullPath: '/settings/delete'
      preLoaderRoute: typeof AuthedSettingsDeleteRouteImport
      parentRoute: typeof AuthedSettingsRouteRoute
    }
    '/_authed/settings/auth': {
      id: '/_authed/settings/auth'
      path: '/auth'
      fullPath: '/settings/auth'
      preLoaderRoute: typeof AuthedSettingsAuthRouteImport
      parentRoute: typeof AuthedSettingsRouteRoute
    }
    '/_authed/enroll/encode': {
      id: '/_authed/enroll/encode'
      path: '/encode'
      fullPath: '/enroll/encode'
      preLoaderRoute: typeof AuthedEnrollEncodeRouteImport
      parentRoute: typeof AuthedEnrollRouteRoute
    }
  }
}

interface AuthedEnrollRouteRouteChildren {
  AuthedEnrollEncodeRoute: typeof AuthedEnrollEncodeRoute
  AuthedEnrollIndexRoute: typeof AuthedEnrollIndexRoute
}

const AuthedEnrollRouteRouteChildren: AuthedEnrollRouteRouteChildren = {
  AuthedEnrollEncodeRoute: AuthedEnrollEncodeRoute,
  AuthedEnrollIndexRoute: AuthedEnrollIndexRoute,
}

const AuthedEnrollRouteRouteWithChildren =
  AuthedEnrollRouteRoute._addFileChildren(AuthedEnrollRouteRouteChildren)

interface AuthedSettingsRouteRouteChildren {
  AuthedSettingsAuthRoute: typeof AuthedSettingsAuthRoute
  AuthedSettingsDeleteRoute: typeof AuthedSettingsDeleteRoute
  AuthedSettingsIndexRoute: typeof AuthedSettingsIndexRoute
}

const AuthedSettingsRouteRouteChildren: AuthedSettingsRouteRouteChildren = {
  AuthedSettingsAuthRoute: AuthedSettingsAuthRoute,
  AuthedSettingsDeleteRoute: AuthedSettingsDeleteRoute,
  AuthedSettingsIndexRoute: AuthedSettingsIndexRoute,
}

const AuthedSettingsRouteRouteWithChildren =
  AuthedSettingsRouteRoute._addFileChildren(AuthedSettingsRouteRouteChildren)

interface AuthedRouteChildren {
  AuthedEnrollRouteRoute: typeof AuthedEnrollRouteRouteWithChildren
  AuthedSettingsRouteRoute: typeof AuthedSettingsRouteRouteWithChildren
  AuthedAccountRoute: typeof AuthedAccountRoute
  AuthedGradesRoute: typeof AuthedGradesRoute
  AuthedRegistrationFormRoute: typeof AuthedRegistrationFormRoute
  AuthedSchedulesRoute: typeof AuthedSchedulesRoute
  AuthedSubjectsRoute: typeof AuthedSubjectsRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedEnrollRouteRoute: AuthedEnrollRouteRouteWithChildren,
  AuthedSettingsRouteRoute: AuthedSettingsRouteRouteWithChildren,
  AuthedAccountRoute: AuthedAccountRoute,
  AuthedGradesRoute: AuthedGradesRoute,
  AuthedRegistrationFormRoute: AuthedRegistrationFormRoute,
  AuthedSchedulesRoute: AuthedSchedulesRoute,
  AuthedSubjectsRoute: AuthedSubjectsRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
